// Code generated by protoc-gen-go. DO NOT EDIT.
// source: city.proto

package hegemonie_region_proto_city

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NamedItem struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedItem) Reset()         { *m = NamedItem{} }
func (m *NamedItem) String() string { return proto.CompactTextString(m) }
func (*NamedItem) ProtoMessage()    {}
func (*NamedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{0}
}

func (m *NamedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedItem.Unmarshal(m, b)
}
func (m *NamedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedItem.Marshal(b, m, deterministic)
}
func (m *NamedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedItem.Merge(m, src)
}
func (m *NamedItem) XXX_Size() int {
	return xxx_messageInfo_NamedItem.Size(m)
}
func (m *NamedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedItem.DiscardUnknown(m)
}

var xxx_messageInfo_NamedItem proto.InternalMessageInfo

func (m *NamedItem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NamedItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListOfNamedItems struct {
	Items                []*NamedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListOfNamedItems) Reset()         { *m = ListOfNamedItems{} }
func (m *ListOfNamedItems) String() string { return proto.CompactTextString(m) }
func (*ListOfNamedItems) ProtoMessage()    {}
func (*ListOfNamedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{1}
}

func (m *ListOfNamedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfNamedItems.Unmarshal(m, b)
}
func (m *ListOfNamedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfNamedItems.Marshal(b, m, deterministic)
}
func (m *ListOfNamedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfNamedItems.Merge(m, src)
}
func (m *ListOfNamedItems) XXX_Size() int {
	return xxx_messageInfo_ListOfNamedItems.Size(m)
}
func (m *ListOfNamedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfNamedItems.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfNamedItems proto.InternalMessageInfo

func (m *ListOfNamedItems) GetItems() []*NamedItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListOfManagedCities struct {
	Items                []*ManagedCity `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListOfManagedCities) Reset()         { *m = ListOfManagedCities{} }
func (m *ListOfManagedCities) String() string { return proto.CompactTextString(m) }
func (*ListOfManagedCities) ProtoMessage()    {}
func (*ListOfManagedCities) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{2}
}

func (m *ListOfManagedCities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfManagedCities.Unmarshal(m, b)
}
func (m *ListOfManagedCities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfManagedCities.Marshal(b, m, deterministic)
}
func (m *ListOfManagedCities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfManagedCities.Merge(m, src)
}
func (m *ListOfManagedCities) XXX_Size() int {
	return xxx_messageInfo_ListOfManagedCities.Size(m)
}
func (m *ListOfManagedCities) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfManagedCities.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfManagedCities proto.InternalMessageInfo

func (m *ListOfManagedCities) GetItems() []*ManagedCity {
	if m != nil {
		return m.Items
	}
	return nil
}

type ManagedCity struct {
	IdCharacter          uint64   `protobuf:"varint,1,opt,name=idCharacter,proto3" json:"idCharacter,omitempty"`
	IdCity               uint64   `protobuf:"varint,2,opt,name=idCity,proto3" json:"idCity,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagedCity) Reset()         { *m = ManagedCity{} }
func (m *ManagedCity) String() string { return proto.CompactTextString(m) }
func (*ManagedCity) ProtoMessage()    {}
func (*ManagedCity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{3}
}

func (m *ManagedCity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedCity.Unmarshal(m, b)
}
func (m *ManagedCity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedCity.Marshal(b, m, deterministic)
}
func (m *ManagedCity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedCity.Merge(m, src)
}
func (m *ManagedCity) XXX_Size() int {
	return xxx_messageInfo_ManagedCity.Size(m)
}
func (m *ManagedCity) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedCity.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedCity proto.InternalMessageInfo

func (m *ManagedCity) GetIdCharacter() uint64 {
	if m != nil {
		return m.IdCharacter
	}
	return 0
}

func (m *ManagedCity) GetIdCity() uint64 {
	if m != nil {
		return m.IdCity
	}
	return 0
}

func (m *ManagedCity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Identifies a City and Character who is
type CityId struct {
	Character            uint64   `protobuf:"varint,1,opt,name=character,proto3" json:"character,omitempty"`
	City                 uint64   `protobuf:"varint,2,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityId) Reset()         { *m = CityId{} }
func (m *CityId) String() string { return proto.CompactTextString(m) }
func (*CityId) ProtoMessage()    {}
func (*CityId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{4}
}

func (m *CityId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityId.Unmarshal(m, b)
}
func (m *CityId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityId.Marshal(b, m, deterministic)
}
func (m *CityId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityId.Merge(m, src)
}
func (m *CityId) XXX_Size() int {
	return xxx_messageInfo_CityId.Size(m)
}
func (m *CityId) XXX_DiscardUnknown() {
	xxx_messageInfo_CityId.DiscardUnknown(m)
}

var xxx_messageInfo_CityId proto.InternalMessageInfo

func (m *CityId) GetCharacter() uint64 {
	if m != nil {
		return m.Character
	}
	return 0
}

func (m *CityId) GetCity() uint64 {
	if m != nil {
		return m.City
	}
	return 0
}

type ArmyView struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArmyView) Reset()         { *m = ArmyView{} }
func (m *ArmyView) String() string { return proto.CompactTextString(m) }
func (*ArmyView) ProtoMessage()    {}
func (*ArmyView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{5}
}

func (m *ArmyView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArmyView.Unmarshal(m, b)
}
func (m *ArmyView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArmyView.Marshal(b, m, deterministic)
}
func (m *ArmyView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArmyView.Merge(m, src)
}
func (m *ArmyView) XXX_Size() int {
	return xxx_messageInfo_ArmyView.Size(m)
}
func (m *ArmyView) XXX_DiscardUnknown() {
	xxx_messageInfo_ArmyView.DiscardUnknown(m)
}

var xxx_messageInfo_ArmyView proto.InternalMessageInfo

func (m *ArmyView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArmyView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResourcesAbs struct {
	R0                   uint64   `protobuf:"varint,1,opt,name=r0,proto3" json:"r0,omitempty"`
	R1                   uint64   `protobuf:"varint,2,opt,name=r1,proto3" json:"r1,omitempty"`
	R2                   uint64   `protobuf:"varint,3,opt,name=r2,proto3" json:"r2,omitempty"`
	R3                   uint64   `protobuf:"varint,4,opt,name=r3,proto3" json:"r3,omitempty"`
	R4                   uint64   `protobuf:"varint,5,opt,name=r4,proto3" json:"r4,omitempty"`
	R5                   uint64   `protobuf:"varint,6,opt,name=r5,proto3" json:"r5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesAbs) Reset()         { *m = ResourcesAbs{} }
func (m *ResourcesAbs) String() string { return proto.CompactTextString(m) }
func (*ResourcesAbs) ProtoMessage()    {}
func (*ResourcesAbs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{6}
}

func (m *ResourcesAbs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesAbs.Unmarshal(m, b)
}
func (m *ResourcesAbs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesAbs.Marshal(b, m, deterministic)
}
func (m *ResourcesAbs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesAbs.Merge(m, src)
}
func (m *ResourcesAbs) XXX_Size() int {
	return xxx_messageInfo_ResourcesAbs.Size(m)
}
func (m *ResourcesAbs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesAbs.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesAbs proto.InternalMessageInfo

func (m *ResourcesAbs) GetR0() uint64 {
	if m != nil {
		return m.R0
	}
	return 0
}

func (m *ResourcesAbs) GetR1() uint64 {
	if m != nil {
		return m.R1
	}
	return 0
}

func (m *ResourcesAbs) GetR2() uint64 {
	if m != nil {
		return m.R2
	}
	return 0
}

func (m *ResourcesAbs) GetR3() uint64 {
	if m != nil {
		return m.R3
	}
	return 0
}

func (m *ResourcesAbs) GetR4() uint64 {
	if m != nil {
		return m.R4
	}
	return 0
}

func (m *ResourcesAbs) GetR5() uint64 {
	if m != nil {
		return m.R5
	}
	return 0
}

type ResourcesPlus struct {
	R0                   int64    `protobuf:"varint,1,opt,name=r0,proto3" json:"r0,omitempty"`
	R1                   int64    `protobuf:"varint,2,opt,name=r1,proto3" json:"r1,omitempty"`
	R2                   int64    `protobuf:"varint,3,opt,name=r2,proto3" json:"r2,omitempty"`
	R3                   int64    `protobuf:"varint,4,opt,name=r3,proto3" json:"r3,omitempty"`
	R4                   int64    `protobuf:"varint,5,opt,name=r4,proto3" json:"r4,omitempty"`
	R5                   int64    `protobuf:"varint,6,opt,name=r5,proto3" json:"r5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesPlus) Reset()         { *m = ResourcesPlus{} }
func (m *ResourcesPlus) String() string { return proto.CompactTextString(m) }
func (*ResourcesPlus) ProtoMessage()    {}
func (*ResourcesPlus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{7}
}

func (m *ResourcesPlus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesPlus.Unmarshal(m, b)
}
func (m *ResourcesPlus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesPlus.Marshal(b, m, deterministic)
}
func (m *ResourcesPlus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesPlus.Merge(m, src)
}
func (m *ResourcesPlus) XXX_Size() int {
	return xxx_messageInfo_ResourcesPlus.Size(m)
}
func (m *ResourcesPlus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesPlus.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesPlus proto.InternalMessageInfo

func (m *ResourcesPlus) GetR0() int64 {
	if m != nil {
		return m.R0
	}
	return 0
}

func (m *ResourcesPlus) GetR1() int64 {
	if m != nil {
		return m.R1
	}
	return 0
}

func (m *ResourcesPlus) GetR2() int64 {
	if m != nil {
		return m.R2
	}
	return 0
}

func (m *ResourcesPlus) GetR3() int64 {
	if m != nil {
		return m.R3
	}
	return 0
}

func (m *ResourcesPlus) GetR4() int64 {
	if m != nil {
		return m.R4
	}
	return 0
}

func (m *ResourcesPlus) GetR5() int64 {
	if m != nil {
		return m.R5
	}
	return 0
}

type ResourcesMult struct {
	R0                   float64  `protobuf:"fixed64,1,opt,name=r0,proto3" json:"r0,omitempty"`
	R1                   float64  `protobuf:"fixed64,2,opt,name=r1,proto3" json:"r1,omitempty"`
	R2                   float64  `protobuf:"fixed64,3,opt,name=r2,proto3" json:"r2,omitempty"`
	R3                   float64  `protobuf:"fixed64,4,opt,name=r3,proto3" json:"r3,omitempty"`
	R4                   float64  `protobuf:"fixed64,5,opt,name=r4,proto3" json:"r4,omitempty"`
	R5                   float64  `protobuf:"fixed64,6,opt,name=r5,proto3" json:"r5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcesMult) Reset()         { *m = ResourcesMult{} }
func (m *ResourcesMult) String() string { return proto.CompactTextString(m) }
func (*ResourcesMult) ProtoMessage()    {}
func (*ResourcesMult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{8}
}

func (m *ResourcesMult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesMult.Unmarshal(m, b)
}
func (m *ResourcesMult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesMult.Marshal(b, m, deterministic)
}
func (m *ResourcesMult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesMult.Merge(m, src)
}
func (m *ResourcesMult) XXX_Size() int {
	return xxx_messageInfo_ResourcesMult.Size(m)
}
func (m *ResourcesMult) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesMult.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesMult proto.InternalMessageInfo

func (m *ResourcesMult) GetR0() float64 {
	if m != nil {
		return m.R0
	}
	return 0
}

func (m *ResourcesMult) GetR1() float64 {
	if m != nil {
		return m.R1
	}
	return 0
}

func (m *ResourcesMult) GetR2() float64 {
	if m != nil {
		return m.R2
	}
	return 0
}

func (m *ResourcesMult) GetR3() float64 {
	if m != nil {
		return m.R3
	}
	return 0
}

func (m *ResourcesMult) GetR4() float64 {
	if m != nil {
		return m.R4
	}
	return 0
}

func (m *ResourcesMult) GetR5() float64 {
	if m != nil {
		return m.R5
	}
	return 0
}

type ResourcesMod struct {
	Plus                 *ResourcesPlus `protobuf:"bytes,1,opt,name=plus,proto3" json:"plus,omitempty"`
	Mult                 *ResourcesMult `protobuf:"bytes,2,opt,name=mult,proto3" json:"mult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResourcesMod) Reset()         { *m = ResourcesMod{} }
func (m *ResourcesMod) String() string { return proto.CompactTextString(m) }
func (*ResourcesMod) ProtoMessage()    {}
func (*ResourcesMod) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{9}
}

func (m *ResourcesMod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesMod.Unmarshal(m, b)
}
func (m *ResourcesMod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesMod.Marshal(b, m, deterministic)
}
func (m *ResourcesMod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesMod.Merge(m, src)
}
func (m *ResourcesMod) XXX_Size() int {
	return xxx_messageInfo_ResourcesMod.Size(m)
}
func (m *ResourcesMod) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesMod.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesMod proto.InternalMessageInfo

func (m *ResourcesMod) GetPlus() *ResourcesPlus {
	if m != nil {
		return m.Plus
	}
	return nil
}

func (m *ResourcesMod) GetMult() *ResourcesMult {
	if m != nil {
		return m.Mult
	}
	return nil
}

type UnitTypeView struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitTypeView) Reset()         { *m = UnitTypeView{} }
func (m *UnitTypeView) String() string { return proto.CompactTextString(m) }
func (*UnitTypeView) ProtoMessage()    {}
func (*UnitTypeView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{10}
}

func (m *UnitTypeView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitTypeView.Unmarshal(m, b)
}
func (m *UnitTypeView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitTypeView.Marshal(b, m, deterministic)
}
func (m *UnitTypeView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitTypeView.Merge(m, src)
}
func (m *UnitTypeView) XXX_Size() int {
	return xxx_messageInfo_UnitTypeView.Size(m)
}
func (m *UnitTypeView) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitTypeView.DiscardUnknown(m)
}

var xxx_messageInfo_UnitTypeView proto.InternalMessageInfo

func (m *UnitTypeView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnitTypeView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BuildingTypeView struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildingTypeView) Reset()         { *m = BuildingTypeView{} }
func (m *BuildingTypeView) String() string { return proto.CompactTextString(m) }
func (*BuildingTypeView) ProtoMessage()    {}
func (*BuildingTypeView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{11}
}

func (m *BuildingTypeView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingTypeView.Unmarshal(m, b)
}
func (m *BuildingTypeView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingTypeView.Marshal(b, m, deterministic)
}
func (m *BuildingTypeView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingTypeView.Merge(m, src)
}
func (m *BuildingTypeView) XXX_Size() int {
	return xxx_messageInfo_BuildingTypeView.Size(m)
}
func (m *BuildingTypeView) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingTypeView.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingTypeView proto.InternalMessageInfo

func (m *BuildingTypeView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildingTypeView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KnowledgeTypeView struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KnowledgeTypeView) Reset()         { *m = KnowledgeTypeView{} }
func (m *KnowledgeTypeView) String() string { return proto.CompactTextString(m) }
func (*KnowledgeTypeView) ProtoMessage()    {}
func (*KnowledgeTypeView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{12}
}

func (m *KnowledgeTypeView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnowledgeTypeView.Unmarshal(m, b)
}
func (m *KnowledgeTypeView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnowledgeTypeView.Marshal(b, m, deterministic)
}
func (m *KnowledgeTypeView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnowledgeTypeView.Merge(m, src)
}
func (m *KnowledgeTypeView) XXX_Size() int {
	return xxx_messageInfo_KnowledgeTypeView.Size(m)
}
func (m *KnowledgeTypeView) XXX_DiscardUnknown() {
	xxx_messageInfo_KnowledgeTypeView.DiscardUnknown(m)
}

var xxx_messageInfo_KnowledgeTypeView proto.InternalMessageInfo

func (m *KnowledgeTypeView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KnowledgeTypeView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnitView struct {
	Type                 *UnitTypeView `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IdType               uint64        `protobuf:"varint,3,opt,name=idType,proto3" json:"idType,omitempty"`
	Ticks                uint32        `protobuf:"varint,4,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Name                 string        `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnitView) Reset()         { *m = UnitView{} }
func (m *UnitView) String() string { return proto.CompactTextString(m) }
func (*UnitView) ProtoMessage()    {}
func (*UnitView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{13}
}

func (m *UnitView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitView.Unmarshal(m, b)
}
func (m *UnitView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitView.Marshal(b, m, deterministic)
}
func (m *UnitView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitView.Merge(m, src)
}
func (m *UnitView) XXX_Size() int {
	return xxx_messageInfo_UnitView.Size(m)
}
func (m *UnitView) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitView.DiscardUnknown(m)
}

var xxx_messageInfo_UnitView proto.InternalMessageInfo

func (m *UnitView) GetType() *UnitTypeView {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *UnitView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnitView) GetIdType() uint64 {
	if m != nil {
		return m.IdType
	}
	return 0
}

func (m *UnitView) GetTicks() uint32 {
	if m != nil {
		return m.Ticks
	}
	return 0
}

func (m *UnitView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BuildingView struct {
	Type                 *BuildingTypeView `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   uint64            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IdType               uint64            `protobuf:"varint,3,opt,name=idType,proto3" json:"idType,omitempty"`
	Ticks                uint32            `protobuf:"varint,4,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Name                 string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BuildingView) Reset()         { *m = BuildingView{} }
func (m *BuildingView) String() string { return proto.CompactTextString(m) }
func (*BuildingView) ProtoMessage()    {}
func (*BuildingView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{14}
}

func (m *BuildingView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingView.Unmarshal(m, b)
}
func (m *BuildingView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingView.Marshal(b, m, deterministic)
}
func (m *BuildingView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingView.Merge(m, src)
}
func (m *BuildingView) XXX_Size() int {
	return xxx_messageInfo_BuildingView.Size(m)
}
func (m *BuildingView) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingView.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingView proto.InternalMessageInfo

func (m *BuildingView) GetType() *BuildingTypeView {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *BuildingView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildingView) GetIdType() uint64 {
	if m != nil {
		return m.IdType
	}
	return 0
}

func (m *BuildingView) GetTicks() uint32 {
	if m != nil {
		return m.Ticks
	}
	return 0
}

func (m *BuildingView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KnowledgeView struct {
	Type                 *KnowledgeTypeView `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   uint64             `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IdType               uint64             `protobuf:"varint,3,opt,name=idType,proto3" json:"idType,omitempty"`
	Ticks                uint32             `protobuf:"varint,4,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Name                 string             `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KnowledgeView) Reset()         { *m = KnowledgeView{} }
func (m *KnowledgeView) String() string { return proto.CompactTextString(m) }
func (*KnowledgeView) ProtoMessage()    {}
func (*KnowledgeView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{15}
}

func (m *KnowledgeView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnowledgeView.Unmarshal(m, b)
}
func (m *KnowledgeView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnowledgeView.Marshal(b, m, deterministic)
}
func (m *KnowledgeView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnowledgeView.Merge(m, src)
}
func (m *KnowledgeView) XXX_Size() int {
	return xxx_messageInfo_KnowledgeView.Size(m)
}
func (m *KnowledgeView) XXX_DiscardUnknown() {
	xxx_messageInfo_KnowledgeView.DiscardUnknown(m)
}

var xxx_messageInfo_KnowledgeView proto.InternalMessageInfo

func (m *KnowledgeView) GetType() *KnowledgeTypeView {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *KnowledgeView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KnowledgeView) GetIdType() uint64 {
	if m != nil {
		return m.IdType
	}
	return 0
}

func (m *KnowledgeView) GetTicks() uint32 {
	if m != nil {
		return m.Ticks
	}
	return 0
}

func (m *KnowledgeView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StockView struct {
	Base                 *ResourcesAbs `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Knowledge            *ResourcesMod `protobuf:"bytes,2,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	Buildings            *ResourcesMod `protobuf:"bytes,3,opt,name=buildings,proto3" json:"buildings,omitempty"`
	Troops               *ResourcesMod `protobuf:"bytes,4,opt,name=troops,proto3" json:"troops,omitempty"`
	Actual               *ResourcesAbs `protobuf:"bytes,5,opt,name=actual,proto3" json:"actual,omitempty"`
	Usage                *ResourcesAbs `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StockView) Reset()         { *m = StockView{} }
func (m *StockView) String() string { return proto.CompactTextString(m) }
func (*StockView) ProtoMessage()    {}
func (*StockView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{16}
}

func (m *StockView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockView.Unmarshal(m, b)
}
func (m *StockView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockView.Marshal(b, m, deterministic)
}
func (m *StockView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockView.Merge(m, src)
}
func (m *StockView) XXX_Size() int {
	return xxx_messageInfo_StockView.Size(m)
}
func (m *StockView) XXX_DiscardUnknown() {
	xxx_messageInfo_StockView.DiscardUnknown(m)
}

var xxx_messageInfo_StockView proto.InternalMessageInfo

func (m *StockView) GetBase() *ResourcesAbs {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *StockView) GetKnowledge() *ResourcesMod {
	if m != nil {
		return m.Knowledge
	}
	return nil
}

func (m *StockView) GetBuildings() *ResourcesMod {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *StockView) GetTroops() *ResourcesMod {
	if m != nil {
		return m.Troops
	}
	return nil
}

func (m *StockView) GetActual() *ResourcesAbs {
	if m != nil {
		return m.Actual
	}
	return nil
}

func (m *StockView) GetUsage() *ResourcesAbs {
	if m != nil {
		return m.Usage
	}
	return nil
}

type ProductionView struct {
	Base                 *ResourcesAbs `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Knowledge            *ResourcesMod `protobuf:"bytes,2,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	Buildings            *ResourcesMod `protobuf:"bytes,3,opt,name=buildings,proto3" json:"buildings,omitempty"`
	Troops               *ResourcesMod `protobuf:"bytes,4,opt,name=troops,proto3" json:"troops,omitempty"`
	Actual               *ResourcesAbs `protobuf:"bytes,5,opt,name=actual,proto3" json:"actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProductionView) Reset()         { *m = ProductionView{} }
func (m *ProductionView) String() string { return proto.CompactTextString(m) }
func (*ProductionView) ProtoMessage()    {}
func (*ProductionView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{17}
}

func (m *ProductionView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductionView.Unmarshal(m, b)
}
func (m *ProductionView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductionView.Marshal(b, m, deterministic)
}
func (m *ProductionView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductionView.Merge(m, src)
}
func (m *ProductionView) XXX_Size() int {
	return xxx_messageInfo_ProductionView.Size(m)
}
func (m *ProductionView) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductionView.DiscardUnknown(m)
}

var xxx_messageInfo_ProductionView proto.InternalMessageInfo

func (m *ProductionView) GetBase() *ResourcesAbs {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ProductionView) GetKnowledge() *ResourcesMod {
	if m != nil {
		return m.Knowledge
	}
	return nil
}

func (m *ProductionView) GetBuildings() *ResourcesMod {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *ProductionView) GetTroops() *ResourcesMod {
	if m != nil {
		return m.Troops
	}
	return nil
}

func (m *ProductionView) GetActual() *ResourcesAbs {
	if m != nil {
		return m.Actual
	}
	return nil
}

type CityEvolution struct {
	KFrontier            []*KnowledgeTypeView `protobuf:"bytes,1,rep,name=kFrontier,proto3" json:"kFrontier,omitempty"`
	BFrontier            []*BuildingTypeView  `protobuf:"bytes,2,rep,name=bFrontier,proto3" json:"bFrontier,omitempty"`
	UFrontier            []*UnitTypeView      `protobuf:"bytes,3,rep,name=uFrontier,proto3" json:"uFrontier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CityEvolution) Reset()         { *m = CityEvolution{} }
func (m *CityEvolution) String() string { return proto.CompactTextString(m) }
func (*CityEvolution) ProtoMessage()    {}
func (*CityEvolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{18}
}

func (m *CityEvolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityEvolution.Unmarshal(m, b)
}
func (m *CityEvolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityEvolution.Marshal(b, m, deterministic)
}
func (m *CityEvolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityEvolution.Merge(m, src)
}
func (m *CityEvolution) XXX_Size() int {
	return xxx_messageInfo_CityEvolution.Size(m)
}
func (m *CityEvolution) XXX_DiscardUnknown() {
	xxx_messageInfo_CityEvolution.DiscardUnknown(m)
}

var xxx_messageInfo_CityEvolution proto.InternalMessageInfo

func (m *CityEvolution) GetKFrontier() []*KnowledgeTypeView {
	if m != nil {
		return m.KFrontier
	}
	return nil
}

func (m *CityEvolution) GetBFrontier() []*BuildingTypeView {
	if m != nil {
		return m.BFrontier
	}
	return nil
}

func (m *CityEvolution) GetUFrontier() []*UnitTypeView {
	if m != nil {
		return m.UFrontier
	}
	return nil
}

type CityAssets struct {
	Units                []*UnitView      `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	Buildings            []*BuildingView  `protobuf:"bytes,2,rep,name=buildings,proto3" json:"buildings,omitempty"`
	Knowledge            []*KnowledgeView `protobuf:"bytes,3,rep,name=knowledge,proto3" json:"knowledge,omitempty"`
	Armies               []*ArmyView      `protobuf:"bytes,4,rep,name=armies,proto3" json:"armies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CityAssets) Reset()         { *m = CityAssets{} }
func (m *CityAssets) String() string { return proto.CompactTextString(m) }
func (*CityAssets) ProtoMessage()    {}
func (*CityAssets) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{19}
}

func (m *CityAssets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityAssets.Unmarshal(m, b)
}
func (m *CityAssets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityAssets.Marshal(b, m, deterministic)
}
func (m *CityAssets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityAssets.Merge(m, src)
}
func (m *CityAssets) XXX_Size() int {
	return xxx_messageInfo_CityAssets.Size(m)
}
func (m *CityAssets) XXX_DiscardUnknown() {
	xxx_messageInfo_CityAssets.DiscardUnknown(m)
}

var xxx_messageInfo_CityAssets proto.InternalMessageInfo

func (m *CityAssets) GetUnits() []*UnitView {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *CityAssets) GetBuildings() []*BuildingView {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *CityAssets) GetKnowledge() []*KnowledgeView {
	if m != nil {
		return m.Knowledge
	}
	return nil
}

func (m *CityAssets) GetArmies() []*ArmyView {
	if m != nil {
		return m.Armies
	}
	return nil
}

type CityView struct {
	Id                   uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                uint64          `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Deputy               uint64          `protobuf:"varint,4,opt,name=deputy,proto3" json:"deputy,omitempty"`
	Production           *ProductionView `protobuf:"bytes,5,opt,name=production,proto3" json:"production,omitempty"`
	Stock                *StockView      `protobuf:"bytes,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Evol                 *CityEvolution  `protobuf:"bytes,7,opt,name=evol,proto3" json:"evol,omitempty"`
	Assets               *CityAssets     `protobuf:"bytes,8,opt,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CityView) Reset()         { *m = CityView{} }
func (m *CityView) String() string { return proto.CompactTextString(m) }
func (*CityView) ProtoMessage()    {}
func (*CityView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{20}
}

func (m *CityView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityView.Unmarshal(m, b)
}
func (m *CityView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityView.Marshal(b, m, deterministic)
}
func (m *CityView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityView.Merge(m, src)
}
func (m *CityView) XXX_Size() int {
	return xxx_messageInfo_CityView.Size(m)
}
func (m *CityView) XXX_DiscardUnknown() {
	xxx_messageInfo_CityView.DiscardUnknown(m)
}

var xxx_messageInfo_CityView proto.InternalMessageInfo

func (m *CityView) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CityView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityView) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *CityView) GetDeputy() uint64 {
	if m != nil {
		return m.Deputy
	}
	return 0
}

func (m *CityView) GetProduction() *ProductionView {
	if m != nil {
		return m.Production
	}
	return nil
}

func (m *CityView) GetStock() *StockView {
	if m != nil {
		return m.Stock
	}
	return nil
}

func (m *CityView) GetEvol() *CityEvolution {
	if m != nil {
		return m.Evol
	}
	return nil
}

func (m *CityView) GetAssets() *CityAssets {
	if m != nil {
		return m.Assets
	}
	return nil
}

type StudyReq struct {
	City                 *CityId  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	KnowledgeType        uint64   `protobuf:"varint,2,opt,name=knowledgeType,proto3" json:"knowledgeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudyReq) Reset()         { *m = StudyReq{} }
func (m *StudyReq) String() string { return proto.CompactTextString(m) }
func (*StudyReq) ProtoMessage()    {}
func (*StudyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{21}
}

func (m *StudyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyReq.Unmarshal(m, b)
}
func (m *StudyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyReq.Marshal(b, m, deterministic)
}
func (m *StudyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyReq.Merge(m, src)
}
func (m *StudyReq) XXX_Size() int {
	return xxx_messageInfo_StudyReq.Size(m)
}
func (m *StudyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyReq.DiscardUnknown(m)
}

var xxx_messageInfo_StudyReq proto.InternalMessageInfo

func (m *StudyReq) GetCity() *CityId {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *StudyReq) GetKnowledgeType() uint64 {
	if m != nil {
		return m.KnowledgeType
	}
	return 0
}

type TrainReq struct {
	City                 *CityId  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	UnitType             uint64   `protobuf:"varint,2,opt,name=unitType,proto3" json:"unitType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainReq) Reset()         { *m = TrainReq{} }
func (m *TrainReq) String() string { return proto.CompactTextString(m) }
func (*TrainReq) ProtoMessage()    {}
func (*TrainReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{22}
}

func (m *TrainReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainReq.Unmarshal(m, b)
}
func (m *TrainReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainReq.Marshal(b, m, deterministic)
}
func (m *TrainReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainReq.Merge(m, src)
}
func (m *TrainReq) XXX_Size() int {
	return xxx_messageInfo_TrainReq.Size(m)
}
func (m *TrainReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrainReq proto.InternalMessageInfo

func (m *TrainReq) GetCity() *CityId {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *TrainReq) GetUnitType() uint64 {
	if m != nil {
		return m.UnitType
	}
	return 0
}

type BuildReq struct {
	City                 *CityId  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	BuildingType         uint64   `protobuf:"varint,2,opt,name=buildingType,proto3" json:"buildingType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildReq) Reset()         { *m = BuildReq{} }
func (m *BuildReq) String() string { return proto.CompactTextString(m) }
func (*BuildReq) ProtoMessage()    {}
func (*BuildReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{23}
}

func (m *BuildReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildReq.Unmarshal(m, b)
}
func (m *BuildReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildReq.Marshal(b, m, deterministic)
}
func (m *BuildReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildReq.Merge(m, src)
}
func (m *BuildReq) XXX_Size() int {
	return xxx_messageInfo_BuildReq.Size(m)
}
func (m *BuildReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildReq.DiscardUnknown(m)
}

var xxx_messageInfo_BuildReq proto.InternalMessageInfo

func (m *BuildReq) GetCity() *CityId {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *BuildReq) GetBuildingType() uint64 {
	if m != nil {
		return m.BuildingType
	}
	return 0
}

type CreateArmyReq struct {
	City                 *CityId  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArmyReq) Reset()         { *m = CreateArmyReq{} }
func (m *CreateArmyReq) String() string { return proto.CompactTextString(m) }
func (*CreateArmyReq) ProtoMessage()    {}
func (*CreateArmyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{24}
}

func (m *CreateArmyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArmyReq.Unmarshal(m, b)
}
func (m *CreateArmyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArmyReq.Marshal(b, m, deterministic)
}
func (m *CreateArmyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArmyReq.Merge(m, src)
}
func (m *CreateArmyReq) XXX_Size() int {
	return xxx_messageInfo_CreateArmyReq.Size(m)
}
func (m *CreateArmyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArmyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArmyReq proto.InternalMessageInfo

func (m *CreateArmyReq) GetCity() *CityId {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *CreateArmyReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TransferUnitReq struct {
	City                 *CityId  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Army                 uint64   `protobuf:"varint,2,opt,name=army,proto3" json:"army,omitempty"`
	Unit                 uint64   `protobuf:"varint,3,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferUnitReq) Reset()         { *m = TransferUnitReq{} }
func (m *TransferUnitReq) String() string { return proto.CompactTextString(m) }
func (*TransferUnitReq) ProtoMessage()    {}
func (*TransferUnitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{25}
}

func (m *TransferUnitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferUnitReq.Unmarshal(m, b)
}
func (m *TransferUnitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferUnitReq.Marshal(b, m, deterministic)
}
func (m *TransferUnitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferUnitReq.Merge(m, src)
}
func (m *TransferUnitReq) XXX_Size() int {
	return xxx_messageInfo_TransferUnitReq.Size(m)
}
func (m *TransferUnitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferUnitReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransferUnitReq proto.InternalMessageInfo

func (m *TransferUnitReq) GetCity() *CityId {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *TransferUnitReq) GetArmy() uint64 {
	if m != nil {
		return m.Army
	}
	return 0
}

func (m *TransferUnitReq) GetUnit() uint64 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type ListReq struct {
	Character            uint64   `protobuf:"varint,1,opt,name=character,proto3" json:"character,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{26}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetCharacter() uint64 {
	if m != nil {
		return m.Character
	}
	return 0
}

type ListSetReq struct {
	Characters           []uint64 `protobuf:"varint,1,rep,packed,name=characters,proto3" json:"characters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSetReq) Reset()         { *m = ListSetReq{} }
func (m *ListSetReq) String() string { return proto.CompactTextString(m) }
func (*ListSetReq) ProtoMessage()    {}
func (*ListSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{27}
}

func (m *ListSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSetReq.Unmarshal(m, b)
}
func (m *ListSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSetReq.Marshal(b, m, deterministic)
}
func (m *ListSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSetReq.Merge(m, src)
}
func (m *ListSetReq) XXX_Size() int {
	return xxx_messageInfo_ListSetReq.Size(m)
}
func (m *ListSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListSetReq proto.InternalMessageInfo

func (m *ListSetReq) GetCharacters() []uint64 {
	if m != nil {
		return m.Characters
	}
	return nil
}

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{28}
}

func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type PaginatedQuery struct {
	Marker               uint64   `protobuf:"varint,1,opt,name=marker,proto3" json:"marker,omitempty"`
	Max                  uint32   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginatedQuery) Reset()         { *m = PaginatedQuery{} }
func (m *PaginatedQuery) String() string { return proto.CompactTextString(m) }
func (*PaginatedQuery) ProtoMessage()    {}
func (*PaginatedQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{29}
}

func (m *PaginatedQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginatedQuery.Unmarshal(m, b)
}
func (m *PaginatedQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginatedQuery.Marshal(b, m, deterministic)
}
func (m *PaginatedQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginatedQuery.Merge(m, src)
}
func (m *PaginatedQuery) XXX_Size() int {
	return xxx_messageInfo_PaginatedQuery.Size(m)
}
func (m *PaginatedQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginatedQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PaginatedQuery proto.InternalMessageInfo

func (m *PaginatedQuery) GetMarker() uint64 {
	if m != nil {
		return m.Marker
	}
	return 0
}

func (m *PaginatedQuery) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type ListOfUnitTypes struct {
	Items                []*UnitTypeView `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListOfUnitTypes) Reset()         { *m = ListOfUnitTypes{} }
func (m *ListOfUnitTypes) String() string { return proto.CompactTextString(m) }
func (*ListOfUnitTypes) ProtoMessage()    {}
func (*ListOfUnitTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{30}
}

func (m *ListOfUnitTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfUnitTypes.Unmarshal(m, b)
}
func (m *ListOfUnitTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfUnitTypes.Marshal(b, m, deterministic)
}
func (m *ListOfUnitTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfUnitTypes.Merge(m, src)
}
func (m *ListOfUnitTypes) XXX_Size() int {
	return xxx_messageInfo_ListOfUnitTypes.Size(m)
}
func (m *ListOfUnitTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfUnitTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfUnitTypes proto.InternalMessageInfo

func (m *ListOfUnitTypes) GetItems() []*UnitTypeView {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListOfBuildingTypes struct {
	Items                []*BuildingTypeView `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListOfBuildingTypes) Reset()         { *m = ListOfBuildingTypes{} }
func (m *ListOfBuildingTypes) String() string { return proto.CompactTextString(m) }
func (*ListOfBuildingTypes) ProtoMessage()    {}
func (*ListOfBuildingTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{31}
}

func (m *ListOfBuildingTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfBuildingTypes.Unmarshal(m, b)
}
func (m *ListOfBuildingTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfBuildingTypes.Marshal(b, m, deterministic)
}
func (m *ListOfBuildingTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfBuildingTypes.Merge(m, src)
}
func (m *ListOfBuildingTypes) XXX_Size() int {
	return xxx_messageInfo_ListOfBuildingTypes.Size(m)
}
func (m *ListOfBuildingTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfBuildingTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfBuildingTypes proto.InternalMessageInfo

func (m *ListOfBuildingTypes) GetItems() []*BuildingTypeView {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListOfKnowledgeTypes struct {
	Items                []*KnowledgeTypeView `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListOfKnowledgeTypes) Reset()         { *m = ListOfKnowledgeTypes{} }
func (m *ListOfKnowledgeTypes) String() string { return proto.CompactTextString(m) }
func (*ListOfKnowledgeTypes) ProtoMessage()    {}
func (*ListOfKnowledgeTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{32}
}

func (m *ListOfKnowledgeTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfKnowledgeTypes.Unmarshal(m, b)
}
func (m *ListOfKnowledgeTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfKnowledgeTypes.Marshal(b, m, deterministic)
}
func (m *ListOfKnowledgeTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfKnowledgeTypes.Merge(m, src)
}
func (m *ListOfKnowledgeTypes) XXX_Size() int {
	return xxx_messageInfo_ListOfKnowledgeTypes.Size(m)
}
func (m *ListOfKnowledgeTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfKnowledgeTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfKnowledgeTypes proto.InternalMessageInfo

func (m *ListOfKnowledgeTypes) GetItems() []*KnowledgeTypeView {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*NamedItem)(nil), "hegemonie.region.proto.city.NamedItem")
	proto.RegisterType((*ListOfNamedItems)(nil), "hegemonie.region.proto.city.ListOfNamedItems")
	proto.RegisterType((*ListOfManagedCities)(nil), "hegemonie.region.proto.city.ListOfManagedCities")
	proto.RegisterType((*ManagedCity)(nil), "hegemonie.region.proto.city.ManagedCity")
	proto.RegisterType((*CityId)(nil), "hegemonie.region.proto.city.CityId")
	proto.RegisterType((*ArmyView)(nil), "hegemonie.region.proto.city.ArmyView")
	proto.RegisterType((*ResourcesAbs)(nil), "hegemonie.region.proto.city.ResourcesAbs")
	proto.RegisterType((*ResourcesPlus)(nil), "hegemonie.region.proto.city.ResourcesPlus")
	proto.RegisterType((*ResourcesMult)(nil), "hegemonie.region.proto.city.ResourcesMult")
	proto.RegisterType((*ResourcesMod)(nil), "hegemonie.region.proto.city.ResourcesMod")
	proto.RegisterType((*UnitTypeView)(nil), "hegemonie.region.proto.city.UnitTypeView")
	proto.RegisterType((*BuildingTypeView)(nil), "hegemonie.region.proto.city.BuildingTypeView")
	proto.RegisterType((*KnowledgeTypeView)(nil), "hegemonie.region.proto.city.KnowledgeTypeView")
	proto.RegisterType((*UnitView)(nil), "hegemonie.region.proto.city.UnitView")
	proto.RegisterType((*BuildingView)(nil), "hegemonie.region.proto.city.BuildingView")
	proto.RegisterType((*KnowledgeView)(nil), "hegemonie.region.proto.city.KnowledgeView")
	proto.RegisterType((*StockView)(nil), "hegemonie.region.proto.city.StockView")
	proto.RegisterType((*ProductionView)(nil), "hegemonie.region.proto.city.ProductionView")
	proto.RegisterType((*CityEvolution)(nil), "hegemonie.region.proto.city.CityEvolution")
	proto.RegisterType((*CityAssets)(nil), "hegemonie.region.proto.city.CityAssets")
	proto.RegisterType((*CityView)(nil), "hegemonie.region.proto.city.CityView")
	proto.RegisterType((*StudyReq)(nil), "hegemonie.region.proto.city.StudyReq")
	proto.RegisterType((*TrainReq)(nil), "hegemonie.region.proto.city.TrainReq")
	proto.RegisterType((*BuildReq)(nil), "hegemonie.region.proto.city.BuildReq")
	proto.RegisterType((*CreateArmyReq)(nil), "hegemonie.region.proto.city.CreateArmyReq")
	proto.RegisterType((*TransferUnitReq)(nil), "hegemonie.region.proto.city.TransferUnitReq")
	proto.RegisterType((*ListReq)(nil), "hegemonie.region.proto.city.ListReq")
	proto.RegisterType((*ListSetReq)(nil), "hegemonie.region.proto.city.ListSetReq")
	proto.RegisterType((*None)(nil), "hegemonie.region.proto.city.None")
	proto.RegisterType((*PaginatedQuery)(nil), "hegemonie.region.proto.city.PaginatedQuery")
	proto.RegisterType((*ListOfUnitTypes)(nil), "hegemonie.region.proto.city.ListOfUnitTypes")
	proto.RegisterType((*ListOfBuildingTypes)(nil), "hegemonie.region.proto.city.ListOfBuildingTypes")
	proto.RegisterType((*ListOfKnowledgeTypes)(nil), "hegemonie.region.proto.city.ListOfKnowledgeTypes")
}

func init() { proto.RegisterFile("city.proto", fileDescriptor_f63625ed15d5bd67) }

var fileDescriptor_f63625ed15d5bd67 = []byte{
	// 1305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xb6, 0x2c, 0xdb, 0xb5, 0x4f, 0xe2, 0xb4, 0x2c, 0x1d, 0xc6, 0x13, 0x18, 0x26, 0x2c, 0x2d,
	0x0d, 0xa5, 0x35, 0x89, 0xd3, 0xd2, 0x19, 0xa0, 0xed, 0x38, 0x29, 0x3f, 0x99, 0x34, 0x25, 0xc8,
	0x09, 0x17, 0xd0, 0x0e, 0x23, 0x5b, 0x1b, 0x67, 0xc7, 0xb6, 0x64, 0x56, 0xab, 0x06, 0xbf, 0x04,
	0x2f, 0xd0, 0x4b, 0x86, 0x77, 0xe1, 0x25, 0xb8, 0x86, 0x7b, 0x5e, 0x80, 0xd9, 0xa3, 0xb5, 0x2c,
	0xa9, 0x8c, 0x25, 0x91, 0xc9, 0x1d, 0x77, 0xda, 0xf5, 0x7e, 0xdf, 0x77, 0xf6, 0xec, 0xd9, 0x6f,
	0x77, 0x0d, 0x30, 0xe0, 0x72, 0xd6, 0x9e, 0x0a, 0x4f, 0x7a, 0xe4, 0xed, 0x33, 0x36, 0x64, 0x13,
	0xcf, 0xe5, 0xac, 0x2d, 0xd8, 0x90, 0x7b, 0x6e, 0xd8, 0xdf, 0x56, 0x43, 0xe8, 0xc7, 0xd0, 0x78,
	0x66, 0x4f, 0x98, 0xb3, 0x2f, 0xd9, 0x84, 0xac, 0x41, 0x99, 0x3b, 0x2d, 0x63, 0xc3, 0xd8, 0xac,
	0x58, 0x65, 0xee, 0x10, 0x02, 0x15, 0xd7, 0x9e, 0xb0, 0x56, 0x79, 0xc3, 0xd8, 0x6c, 0x58, 0xf8,
	0x4d, 0x8f, 0xe0, 0xda, 0x53, 0xee, 0xcb, 0x6f, 0x4e, 0x23, 0x98, 0x4f, 0x3e, 0x87, 0x2a, 0x57,
	0x1f, 0x2d, 0x63, 0xc3, 0xdc, 0x5c, 0xe9, 0x7c, 0xd0, 0x5e, 0xa2, 0xd8, 0x8e, 0x70, 0x56, 0x08,
	0xa2, 0x27, 0xf0, 0x66, 0xc8, 0x78, 0x68, 0xbb, 0xf6, 0x90, 0x39, 0x7b, 0x5c, 0x72, 0xe6, 0x93,
	0x47, 0x49, 0xd2, 0xcd, 0xa5, 0xa4, 0x0b, 0xe8, 0x6c, 0x4e, 0xfb, 0x03, 0xac, 0xc4, 0x7a, 0xc9,
	0x06, 0xac, 0x70, 0x67, 0xef, 0xcc, 0x16, 0xf6, 0x40, 0x32, 0xa1, 0x27, 0x19, 0xef, 0x22, 0x6f,
	0x41, 0x8d, 0xe3, 0x58, 0x9c, 0x6f, 0xc5, 0xd2, 0xad, 0x28, 0x0b, 0x66, 0x2c, 0x0b, 0x9f, 0x42,
	0x4d, 0xfd, 0xb6, 0xef, 0x90, 0x77, 0xa0, 0x31, 0x48, 0xb1, 0x2e, 0x3a, 0x14, 0x76, 0xb0, 0x60,
	0xc4, 0x6f, 0xda, 0x86, 0x7a, 0x57, 0x4c, 0x66, 0xdf, 0x71, 0x76, 0x9e, 0x2b, 0xe3, 0x2e, 0xac,
	0x5a, 0xcc, 0xf7, 0x02, 0x31, 0x60, 0x7e, 0xb7, 0xef, 0x2b, 0x8c, 0xd8, 0x9a, 0x63, 0xc4, 0x16,
	0xb6, 0xb7, 0xb5, 0x42, 0x59, 0x6c, 0x63, 0xbb, 0x83, 0xd1, 0xaa, 0x76, 0x07, 0xdb, 0x3b, 0xad,
	0x8a, 0x6e, 0xef, 0x60, 0xfb, 0x5e, 0xab, 0xaa, 0xdb, 0xf7, 0xb0, 0x7d, 0xbf, 0x55, 0xd3, 0xed,
	0xfb, 0xd4, 0x83, 0x66, 0xa4, 0x77, 0x34, 0x0e, 0xe2, 0x82, 0x66, 0x4a, 0xd0, 0x4c, 0x09, 0x9a,
	0x29, 0x41, 0x33, 0x25, 0x68, 0xa6, 0x04, 0xcd, 0xd7, 0x04, 0x0f, 0x83, 0xb1, 0x8c, 0x09, 0x1a,
	0x29, 0x41, 0x23, 0x25, 0x68, 0xa4, 0x04, 0x8d, 0x94, 0xa0, 0x91, 0x12, 0x34, 0x50, 0xf0, 0x17,
	0x23, 0x96, 0xd2, 0x43, 0xcf, 0x21, 0x8f, 0xa0, 0x32, 0x1d, 0x07, 0x3e, 0x4a, 0xae, 0x74, 0x6e,
	0x2f, 0x2d, 0xb5, 0x44, 0x6e, 0x2c, 0xc4, 0x29, 0xfc, 0x24, 0x18, 0x4b, 0x0c, 0x31, 0x37, 0x5e,
	0x4d, 0xd5, 0x42, 0x1c, 0xed, 0xc0, 0xea, 0x89, 0xcb, 0xe5, 0xf1, 0x6c, 0xca, 0x72, 0x97, 0xc5,
	0x27, 0x70, 0x6d, 0x37, 0xe0, 0x63, 0x87, 0xbb, 0xc3, 0x42, 0xb8, 0x07, 0xf0, 0xc6, 0x81, 0xeb,
	0x9d, 0x8f, 0x99, 0x33, 0x64, 0x85, 0x80, 0xaf, 0x0c, 0xa8, 0xab, 0x28, 0x11, 0xf0, 0x10, 0x2a,
	0x72, 0x36, 0x65, 0x3a, 0x63, 0x1f, 0x2e, 0x9d, 0x71, 0x7c, 0x6a, 0x16, 0xc2, 0xb4, 0x5e, 0x39,
	0xd2, 0xc3, 0xbd, 0xa7, 0xc6, 0xe8, 0xba, 0xd5, 0x2d, 0x72, 0x1d, 0xaa, 0x92, 0x0f, 0x46, 0x3e,
	0x2e, 0x6e, 0xd3, 0x0a, 0x1b, 0x51, 0x74, 0xd5, 0x58, 0x74, 0xbf, 0x1a, 0xb0, 0x3a, 0xcf, 0x07,
	0x46, 0xd8, 0x4d, 0x44, 0x78, 0x77, 0x69, 0x84, 0xe9, 0x44, 0x5e, 0x5a, 0x94, 0xbf, 0x19, 0xd0,
	0x8c, 0xb2, 0x8f, 0x61, 0xee, 0x26, 0xc2, 0x6c, 0x2f, 0x0d, 0xf3, 0xb5, 0x75, 0xbb, 0xbc, 0x6c,
	0x9a, 0xd0, 0xe8, 0x49, 0x6f, 0x30, 0x9a, 0x2f, 0x76, 0xdf, 0xf6, 0xf3, 0x2d, 0x76, 0xdc, 0xaa,
	0x2c, 0x84, 0x91, 0xaf, 0xa0, 0x31, 0x9a, 0x47, 0xae, 0xb7, 0x48, 0x4e, 0x8e, 0x43, 0xcf, 0xb1,
	0x16, 0x58, 0x45, 0xd4, 0xd7, 0x2b, 0xe5, 0xe3, 0xd4, 0x8a, 0x11, 0x45, 0x58, 0xd2, 0x85, 0x9a,
	0x14, 0x9e, 0x37, 0x0d, 0x33, 0x51, 0x88, 0x45, 0x03, 0x15, 0x85, 0x3d, 0x90, 0x81, 0x3d, 0xc6,
	0xbc, 0x15, 0xca, 0x8a, 0x06, 0x92, 0xc7, 0x50, 0x0d, 0x7c, 0x7b, 0xc8, 0xd0, 0x99, 0x0a, 0x31,
	0x84, 0x38, 0xfa, 0x67, 0x19, 0xd6, 0x8e, 0x84, 0xe7, 0x04, 0x03, 0xc9, 0x3d, 0xf7, 0xff, 0xa5,
	0xba, 0xb4, 0xa5, 0xa2, 0x7f, 0x1b, 0xd0, 0x54, 0x07, 0xfe, 0x17, 0x2f, 0xbd, 0x71, 0xa0, 0x92,
	0x4d, 0x9e, 0x42, 0x63, 0xf4, 0xa5, 0xf0, 0x5c, 0xc9, 0xf1, 0xdc, 0x37, 0xff, 0xc3, 0xe6, 0x5d,
	0x10, 0x90, 0x03, 0x68, 0xf4, 0x23, 0xb6, 0x32, 0xb2, 0x15, 0x74, 0xac, 0x05, 0x5e, 0xe5, 0x3e,
	0x88, 0xc8, 0x4c, 0x24, 0x2b, 0x60, 0xd0, 0x0b, 0x2c, 0x7d, 0x55, 0x06, 0x50, 0xb3, 0xee, 0xfa,
	0x3e, 0x93, 0x3e, 0xf9, 0x0c, 0xaa, 0x81, 0xcb, 0xe5, 0xfc, 0x46, 0x76, 0x33, 0x93, 0x13, 0xf9,
	0x42, 0x4c, 0xb2, 0x20, 0xca, 0x39, 0x82, 0x8a, 0x9b, 0x79, 0xbc, 0x20, 0xbe, 0x8e, 0x97, 0x68,
	0x38, 0xbb, 0xdb, 0xf9, 0x12, 0xaf, 0x93, 0x1e, 0xd5, 0xe8, 0x43, 0xa8, 0xd9, 0x62, 0xc2, 0x99,
	0x2a, 0xad, 0xec, 0x09, 0xcd, 0xef, 0x6c, 0x96, 0x06, 0xd1, 0xbf, 0xca, 0x50, 0x57, 0xd9, 0xc9,
	0x7b, 0x80, 0x2a, 0xfb, 0xf5, 0xce, 0x5d, 0x5c, 0x13, 0x35, 0x2c, 0x6c, 0x28, 0xb3, 0x76, 0xd8,
	0x34, 0x90, 0x33, 0x7d, 0x45, 0xd3, 0x2d, 0x72, 0x00, 0x30, 0x8d, 0xf6, 0xb6, 0xae, 0xdc, 0x8f,
	0x96, 0x46, 0x98, 0xb4, 0x02, 0x2b, 0x06, 0x57, 0x37, 0x74, 0x5f, 0xd9, 0xb9, 0xb6, 0x9a, 0xe5,
	0x37, 0xf4, 0xc8, 0xf8, 0xad, 0x10, 0xa4, 0xae, 0x37, 0xec, 0xa5, 0x37, 0x6e, 0x5d, 0xc9, 0x71,
	0xbd, 0x49, 0xec, 0x12, 0x0b, 0x71, 0xe4, 0x31, 0xd4, 0x6c, 0x2c, 0xa1, 0x56, 0x1d, 0x19, 0x6e,
	0x65, 0x32, 0x84, 0x15, 0x67, 0x69, 0x18, 0xe5, 0x50, 0xef, 0xc9, 0xc0, 0x99, 0x59, 0xec, 0x27,
	0xf2, 0x40, 0x5f, 0xa9, 0x43, 0x87, 0x7b, 0x3f, 0x93, 0x6a, 0xdf, 0x09, 0xef, 0xdd, 0xe4, 0x06,
	0x34, 0x47, 0xf1, 0x3d, 0xa8, 0x0f, 0xcc, 0x64, 0x27, 0xfd, 0x11, 0xea, 0xc7, 0xc2, 0xe6, 0xee,
	0x85, 0xa4, 0xd6, 0xa1, 0x1e, 0xe8, 0x3d, 0xa5, 0x55, 0xa2, 0x36, 0x1d, 0x42, 0x1d, 0x4b, 0xfb,
	0x42, 0x02, 0x14, 0x56, 0xfb, 0x31, 0x07, 0xd0, 0x22, 0x89, 0x3e, 0xfa, 0x1c, 0x9a, 0x7b, 0x82,
	0xd9, 0x92, 0xa9, 0xca, 0xbd, 0x90, 0xda, 0xbf, 0xdd, 0x06, 0x05, 0x5c, 0x3d, 0x16, 0xb6, 0xeb,
	0x9f, 0x32, 0xa1, 0xb6, 0xfa, 0x45, 0xf9, 0x6d, 0x31, 0x89, 0x5e, 0x49, 0xea, 0x5b, 0xf5, 0xa9,
	0x94, 0xe9, 0xbd, 0x82, 0xdf, 0xf4, 0x16, 0x5c, 0x51, 0x2f, 0x45, 0xa5, 0xb5, 0xf4, 0xd9, 0x45,
	0xef, 0x00, 0xa8, 0x81, 0x3d, 0x86, 0x63, 0xdf, 0x05, 0x88, 0x7e, 0x0a, 0xcd, 0xab, 0x62, 0xc5,
	0x7a, 0x68, 0x0d, 0x2a, 0xcf, 0x3c, 0x57, 0x3d, 0xea, 0xd6, 0x8e, 0xec, 0x21, 0x77, 0x6d, 0xc9,
	0x9c, 0x6f, 0x03, 0x26, 0x66, 0x6a, 0x6f, 0x4e, 0x6c, 0x31, 0x8a, 0x24, 0x74, 0x8b, 0x5c, 0x03,
	0x73, 0x62, 0xff, 0x8c, 0xf1, 0x36, 0x2d, 0xf5, 0x49, 0x2d, 0xb8, 0x1a, 0x3e, 0x62, 0xe7, 0x5e,
	0xea, 0xab, 0xe3, 0x3d, 0xfe, 0x80, 0x2d, 0x60, 0xc1, 0xfa, 0x05, 0xfb, 0xfd, 0xfc, 0x61, 0x1c,
	0x37, 0x7b, 0x9f, 0xec, 0x25, 0x79, 0x0b, 0x9e, 0x13, 0x9a, 0xfb, 0x39, 0x5c, 0x0f, 0xb9, 0x13,
	0xc7, 0x92, 0x4f, 0x9e, 0x24, 0xc9, 0x8b, 0x1e, 0x69, 0x21, 0xb8, 0xf3, 0x7b, 0x0d, 0x2a, 0xf8,
	0x76, 0x3e, 0x0d, 0x57, 0xac, 0xc7, 0x24, 0x59, 0xbe, 0xe9, 0x17, 0xcb, 0xb5, 0xbe, 0x95, 0x39,
	0x30, 0xf5, 0x57, 0x01, 0x2d, 0x91, 0x17, 0x50, 0x51, 0x3f, 0x90, 0x1b, 0x99, 0x58, 0xa5, 0x70,
	0x37, 0x87, 0xc2, 0xe2, 0xef, 0x0d, 0x5a, 0x22, 0xc7, 0x50, 0xe9, 0x9d, 0x79, 0xe7, 0x24, 0x4f,
	0x4d, 0xaf, 0xdf, 0xcc, 0x1c, 0xa4, 0x52, 0x45, 0x4b, 0xa4, 0x07, 0x55, 0x74, 0x35, 0x72, 0x33,
	0xc3, 0x8e, 0x43, 0xe7, 0x5b, 0x7f, 0x6f, 0xf9, 0xff, 0x2a, 0xaa, 0x84, 0x91, 0x14, 0xd7, 0x3c,
	0x83, 0x74, 0x6e, 0x41, 0xb9, 0x49, 0xd1, 0x14, 0x33, 0x48, 0xe7, 0xc6, 0x99, 0x8f, 0xf4, 0x05,
	0xc0, 0xc2, 0x9f, 0x48, 0xc6, 0xa9, 0x12, 0x37, 0xb2, 0x7c, 0xf4, 0x36, 0xac, 0xc6, 0x0d, 0x8a,
	0xdc, 0xc9, 0x0a, 0x3d, 0xee, 0x65, 0xf9, 0x24, 0xfa, 0xa1, 0xcd, 0x74, 0xf1, 0x3e, 0x90, 0xaf,
	0x38, 0x8a, 0x96, 0x5e, 0xe7, 0x8f, 0x32, 0xac, 0x3c, 0x61, 0xa7, 0xdc, 0xe5, 0xea, 0x40, 0xf5,
	0xc9, 0x19, 0x34, 0xd4, 0xa8, 0x13, 0xbc, 0x54, 0x65, 0xdc, 0x07, 0x12, 0x66, 0xb6, 0x7e, 0x27,
	0x87, 0x74, 0xe4, 0x5e, 0xb4, 0x44, 0xa6, 0xd0, 0x54, 0x9d, 0xbb, 0xd1, 0xcd, 0xab, 0x90, 0x5a,
	0x9e, 0x5d, 0x9c, 0xf0, 0x35, 0x5a, 0x22, 0x02, 0xd6, 0xd4, 0x0f, 0x91, 0xad, 0x14, 0x94, 0xdc,
	0xce, 0x21, 0x99, 0xb4, 0x3b, 0x5a, 0xea, 0xd7, 0x70, 0xc8, 0xce, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0x84, 0xc2, 0x97, 0x32, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CityClient is the client API for City service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityClient interface {
	// Returns a list of cities owned by the any of the given characters
	ListSet(ctx context.Context, in *ListSetReq, opts ...grpc.CallOption) (*ListOfManagedCities, error)
	// Returns a list of cities owned by the given character
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListOfNamedItems, error)
	// Returns a view of the City
	// Be careful, the request might fail because of a too large object.
	Show(ctx context.Context, in *CityId, opts ...grpc.CallOption) (*CityView, error)
	Study(ctx context.Context, in *StudyReq, opts ...grpc.CallOption) (*None, error)
	Build(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*None, error)
	Train(ctx context.Context, in *TrainReq, opts ...grpc.CallOption) (*None, error)
	CreateArmy(ctx context.Context, in *CreateArmyReq, opts ...grpc.CallOption) (*None, error)
	TransferUnit(ctx context.Context, in *TransferUnitReq, opts ...grpc.CallOption) (*None, error)
	// Return the list of armies that can be controlled by the given City
	ListArmies(ctx context.Context, in *CityId, opts ...grpc.CallOption) (*ListOfNamedItems, error)
}

type cityClient struct {
	cc *grpc.ClientConn
}

func NewCityClient(cc *grpc.ClientConn) CityClient {
	return &cityClient{cc}
}

func (c *cityClient) ListSet(ctx context.Context, in *ListSetReq, opts ...grpc.CallOption) (*ListOfManagedCities, error) {
	out := new(ListOfManagedCities)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/ListSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListOfNamedItems, error) {
	out := new(ListOfNamedItems)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) Show(ctx context.Context, in *CityId, opts ...grpc.CallOption) (*CityView, error) {
	out := new(CityView)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) Study(ctx context.Context, in *StudyReq, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/Study", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) Build(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) Train(ctx context.Context, in *TrainReq, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/Train", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) CreateArmy(ctx context.Context, in *CreateArmyReq, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/CreateArmy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) TransferUnit(ctx context.Context, in *TransferUnitReq, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/TransferUnit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityClient) ListArmies(ctx context.Context, in *CityId, opts ...grpc.CallOption) (*ListOfNamedItems, error) {
	out := new(ListOfNamedItems)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.City/ListArmies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityServer is the server API for City service.
type CityServer interface {
	// Returns a list of cities owned by the any of the given characters
	ListSet(context.Context, *ListSetReq) (*ListOfManagedCities, error)
	// Returns a list of cities owned by the given character
	List(context.Context, *ListReq) (*ListOfNamedItems, error)
	// Returns a view of the City
	// Be careful, the request might fail because of a too large object.
	Show(context.Context, *CityId) (*CityView, error)
	Study(context.Context, *StudyReq) (*None, error)
	Build(context.Context, *BuildReq) (*None, error)
	Train(context.Context, *TrainReq) (*None, error)
	CreateArmy(context.Context, *CreateArmyReq) (*None, error)
	TransferUnit(context.Context, *TransferUnitReq) (*None, error)
	// Return the list of armies that can be controlled by the given City
	ListArmies(context.Context, *CityId) (*ListOfNamedItems, error)
}

// UnimplementedCityServer can be embedded to have forward compatible implementations.
type UnimplementedCityServer struct {
}

func (*UnimplementedCityServer) ListSet(ctx context.Context, req *ListSetReq) (*ListOfManagedCities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSet not implemented")
}
func (*UnimplementedCityServer) List(ctx context.Context, req *ListReq) (*ListOfNamedItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCityServer) Show(ctx context.Context, req *CityId) (*CityView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (*UnimplementedCityServer) Study(ctx context.Context, req *StudyReq) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Study not implemented")
}
func (*UnimplementedCityServer) Build(ctx context.Context, req *BuildReq) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (*UnimplementedCityServer) Train(ctx context.Context, req *TrainReq) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Train not implemented")
}
func (*UnimplementedCityServer) CreateArmy(ctx context.Context, req *CreateArmyReq) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArmy not implemented")
}
func (*UnimplementedCityServer) TransferUnit(ctx context.Context, req *TransferUnitReq) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferUnit not implemented")
}
func (*UnimplementedCityServer) ListArmies(ctx context.Context, req *CityId) (*ListOfNamedItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArmies not implemented")
}

func RegisterCityServer(s *grpc.Server, srv CityServer) {
	s.RegisterService(&_City_serviceDesc, srv)
}

func _City_ListSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).ListSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/ListSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).ListSet(ctx, req.(*ListSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).Show(ctx, req.(*CityId))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_Study_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).Study(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/Study",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).Study(ctx, req.(*StudyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).Build(ctx, req.(*BuildReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/Train",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).Train(ctx, req.(*TrainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_CreateArmy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArmyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).CreateArmy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/CreateArmy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).CreateArmy(ctx, req.(*CreateArmyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_TransferUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferUnitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).TransferUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/TransferUnit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).TransferUnit(ctx, req.(*TransferUnitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _City_ListArmies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServer).ListArmies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.City/ListArmies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServer).ListArmies(ctx, req.(*CityId))
	}
	return interceptor(ctx, in, info, handler)
}

var _City_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hegemonie.region.proto.city.City",
	HandlerType: (*CityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSet",
			Handler:    _City_ListSet_Handler,
		},
		{
			MethodName: "List",
			Handler:    _City_List_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _City_Show_Handler,
		},
		{
			MethodName: "Study",
			Handler:    _City_Study_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _City_Build_Handler,
		},
		{
			MethodName: "Train",
			Handler:    _City_Train_Handler,
		},
		{
			MethodName: "CreateArmy",
			Handler:    _City_CreateArmy_Handler,
		},
		{
			MethodName: "TransferUnit",
			Handler:    _City_TransferUnit_Handler,
		},
		{
			MethodName: "ListArmies",
			Handler:    _City_ListArmies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city.proto",
}

// DefinitionsClient is the client API for Definitions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DefinitionsClient interface {
	ListUnits(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfUnitTypes, error)
	ListBuildings(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfBuildingTypes, error)
	ListKnowledges(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfKnowledgeTypes, error)
}

type definitionsClient struct {
	cc *grpc.ClientConn
}

func NewDefinitionsClient(cc *grpc.ClientConn) DefinitionsClient {
	return &definitionsClient{cc}
}

func (c *definitionsClient) ListUnits(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfUnitTypes, error) {
	out := new(ListOfUnitTypes)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.Definitions/ListUnits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *definitionsClient) ListBuildings(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfBuildingTypes, error) {
	out := new(ListOfBuildingTypes)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.Definitions/ListBuildings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *definitionsClient) ListKnowledges(ctx context.Context, in *PaginatedQuery, opts ...grpc.CallOption) (*ListOfKnowledgeTypes, error) {
	out := new(ListOfKnowledgeTypes)
	err := c.cc.Invoke(ctx, "/hegemonie.region.proto.city.Definitions/ListKnowledges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefinitionsServer is the server API for Definitions service.
type DefinitionsServer interface {
	ListUnits(context.Context, *PaginatedQuery) (*ListOfUnitTypes, error)
	ListBuildings(context.Context, *PaginatedQuery) (*ListOfBuildingTypes, error)
	ListKnowledges(context.Context, *PaginatedQuery) (*ListOfKnowledgeTypes, error)
}

// UnimplementedDefinitionsServer can be embedded to have forward compatible implementations.
type UnimplementedDefinitionsServer struct {
}

func (*UnimplementedDefinitionsServer) ListUnits(ctx context.Context, req *PaginatedQuery) (*ListOfUnitTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnits not implemented")
}
func (*UnimplementedDefinitionsServer) ListBuildings(ctx context.Context, req *PaginatedQuery) (*ListOfBuildingTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuildings not implemented")
}
func (*UnimplementedDefinitionsServer) ListKnowledges(ctx context.Context, req *PaginatedQuery) (*ListOfKnowledgeTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKnowledges not implemented")
}

func RegisterDefinitionsServer(s *grpc.Server, srv DefinitionsServer) {
	s.RegisterService(&_Definitions_serviceDesc, srv)
}

func _Definitions_ListUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginatedQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionsServer).ListUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.Definitions/ListUnits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionsServer).ListUnits(ctx, req.(*PaginatedQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Definitions_ListBuildings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginatedQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionsServer).ListBuildings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.Definitions/ListBuildings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionsServer).ListBuildings(ctx, req.(*PaginatedQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Definitions_ListKnowledges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginatedQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionsServer).ListKnowledges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hegemonie.region.proto.city.Definitions/ListKnowledges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionsServer).ListKnowledges(ctx, req.(*PaginatedQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Definitions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hegemonie.region.proto.city.Definitions",
	HandlerType: (*DefinitionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUnits",
			Handler:    _Definitions_ListUnits_Handler,
		},
		{
			MethodName: "ListBuildings",
			Handler:    _Definitions_ListBuildings_Handler,
		},
		{
			MethodName: "ListKnowledges",
			Handler:    _Definitions_ListKnowledges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city.proto",
}
