name: "Hegemonie"
baseurl: https://www.hegemonie.be
shorturl: https://hegemonie.be
title: Civ-like Diplomacy online RPG
description: Civ-like Diplomacy online RPG
site_description: |-
  Hegemonie.be is game engine for Civ-Like 4X diplomacy RPG.
  For human-scale communities loving roleplay game with rich narrative frames.
keywords: |-
  online rpg, roleplay game, online game, game engine, gamemaster, NPC, non payable characters,
  diplomacy rpg, diplomacy game, diplomacy online rpg,
  civ-like RPG, civilization, 4X, medfan, medieval, fantastic
next: index.html
prev: index.html
author: jfsmig
